# Generated by Django 2.0 on 2018-06-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submitter',
        ),
        migrations.AlterField(
            model_name='question',
            name='answerer',
            field=models.CharField(max_length=50, verbose_name='Subitter'),
        ),
    ]
