# Generated by Django 2.0 on 2018-06-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0002_auto_20180614_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submitter',
            field=models.CharField(default='', max_length=50, verbose_name='Submitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answerer',
            field=models.CharField(max_length=50, verbose_name='Answerer'),
        ),
    ]
