# Generated by Django 2.0 on 2018-06-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0003_auto_20180614_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Answerer')),
                ('text', models.TextField(verbose_name='Question')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date submitted')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answerer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submitter',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
