# Generated by Django 2.0 on 2018-06-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0004_auto_20180614_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zr.Answer'),
            preserve_default=False,
        ),
    ]
