# Generated by Django 2.0 on 2018-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0007_auto_20180614_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Answer'),
        ),
    ]
