# Generated by Django 2.0 on 2018-06-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0008_auto_20180614_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers',
            new_name='answer',
        ),
    ]
