# Generated by Django 2.0 on 2018-06-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zr', '0009_auto_20180614_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='datetime',
            new_name='date',
        ),
    ]
